# curl 'http://localhost:9090/demo'
#--header 'Authorization: Bearer eyJraWQiOiJlNmI4YjFiOC1hMGVjLTRmZGMtOTM1My1iOWIxNTk2MjExZTIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtb2UiLCJhdWQiOiJjbGllbnQiLCJuYmYiOjE3MTEzMDA1NTQsInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3MTEzMDA4NTQsImlhdCI6MTcxMTMwMDU1NCwianRpIjoiNzdkOTAxZGMtNjQ2Zi00NzU0LThmOWQtYzIwMGY0ZGYzMzcxIn0.QqDDFg74dvKu0nDxNnYZgUfxmhS65EC4TyaCwHmtcVAVAZtVsFfbxw6rmM090zC-JPa7OgZvDwjJylwp5w-PhFEF9HoEtCk-EjMugExJUpqDu1BCk0BgiOrg19CuUB3tverawZLL1Ck4pwSs6T6KIzYz3TKiv4FLMpjdRNAaAbejX-J3fgiLcVHoCNQMqSmtEAgNrg0bZqLpHB4P1MDnIs_Ga-uJXPkoogEnPejcD9zs5BkHsYCnVxbsb7Gvhrkq0YvBErnsQJgEnXeJtcZkcwK9WusnAdOqdaiiPng2Gt05Che-qJISwSURqg-0Mh5Oah6wYeW7KpQe0bBzaBZppw
GET http://localhost:9090/demo
Authorization: Bearer eyJraWQiOiJlNmI4YjFiOC1hMGVjLTRmZGMtOTM1My1iOWIxNTk2MjExZTIiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJtb2UiLCJhdWQiOiJjbGllbnQiLCJuYmYiOjE3MTEzMDA1NTQsInNjb3BlIjpbIm9wZW5pZCJdLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODAiLCJleHAiOjE3MTEzMDA4NTQsImlhdCI6MTcxMTMwMDU1NCwianRpIjoiNzdkOTAxZGMtNjQ2Zi00NzU0LThmOWQtYzIwMGY0ZGYzMzcxIn0.QqDDFg74dvKu0nDxNnYZgUfxmhS65EC4TyaCwHmtcVAVAZtVsFfbxw6rmM090zC-JPa7OgZvDwjJylwp5w-PhFEF9HoEtCk-EjMugExJUpqDu1BCk0BgiOrg19CuUB3tverawZLL1Ck4pwSs6T6KIzYz3TKiv4FLMpjdRNAaAbejX-J3fgiLcVHoCNQMqSmtEAgNrg0bZqLpHB4P1MDnIs_Ga-uJXPkoogEnPejcD9zs5BkHsYCnVxbsb7Gvhrkq0YvBErnsQJgEnXeJtcZkcwK9WusnAdOqdaiiPng2Gt05Che-qJISwSURqg-0Mh5Oah6wYeW7KpQe0bBzaBZppw

###